# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_name', models.CharField(default='Ruha', max_length=200)),
                ('Meretek', models.CharField(default='Ruha', max_length=200)),
                ('Anyag', models.CharField(default='Ruha', max_length=200)),
                ('Ar', models.CharField(default='Ruha', max_length=200)),
                ('main_image', models.FileField(upload_to='uploads/')),
                ('alt1_image', models.FileField(upload_to='uploads/')),
                ('alt2_image', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
